---
# Variables that apply to all servers
cloudflare_api_token: "{{ vault_cloudflare_api_token }}" # Still use Ansible Vault!

crowdsec_api_key: "{{ vault_crowdsec_api_key }}" # optional (key will be generated)
crowdsec_enrollment_key: "{{ vault_crowdsec_enrollment_key }}" # enrollment key for crowdsec security engine, connect with console

# EXPERIMENTAL
# Global toggle for Cloudflare DNS challenges
enable_cloudflare: false # Set to 'false' to disable Cloudflare DNS and its Caddy plugin

# Global toggle for CrowdSec integration
enable_crowdsec: true   # Set to 'false' to disable CrowdSec installation and its Caddy plugin