# roles/xcaddy/tasks/main.yml

- name: Ensure xcaddy installation path exists
  ansible.builtin.file:
    path: "{{ xcaddy_install_path }}" # e.g., /usr/local/bin
    state: directory
    mode: "0755"

- name: Check current xcaddy version
  ansible.builtin.command:
    cmd: "{{ xcaddy_install_path }}/xcaddy --version"
  register: xcaddy_version_check
  ignore_errors: true
  changed_when: false

- name: Set xcaddy version changed flag
  ansible.builtin.set_fact:
    xcaddy_version_changed: >-
      {{ xcaddy_version_check.stdout is not defined
         or xcaddy_version_check.rc != 0
         or not (xcaddy_version_check.stdout.split()[0] | regex_replace('^v', '') == xcaddy_version) }}

- name: Display xcaddy version change message
  ansible.builtin.debug:
    msg: >
      Current xcaddy version: {{ xcaddy_version_check.stdout | default('not installed') }}.
      Target version: {{ xcaddy_version }}.
      Version changed: {{ xcaddy_version_changed }}.

- name: Download xcaddy tarball if version has changed
  ansible.builtin.get_url:
    url: "{{ xcaddy_download_url }}"
    dest: "/tmp/xcaddy_temp.tar.gz"
    mode: "0644"
  when: xcaddy_version_changed
  register: xcaddy_download_result
  until: xcaddy_download_result is succeeded
  retries: 5
  delay: 2 # Retry download up to 5 times with a 2-second delay

- name: Extract xcaddy binary from tarball
  ansible.builtin.unarchive:
    src: "/tmp/xcaddy_temp.tar.gz"
    dest: "/tmp/"
    remote_src: true
    creates: "/tmp/xcaddy" # Idempotent: only extract if binary doesn't exist
  when: xcaddy_version_changed

- name: Move xcaddy to installation directory
  ansible.builtin.copy:
    src: "/tmp/xcaddy"
    dest: "{{ xcaddy_install_path }}/xcaddy"
    owner: root
    group: root
    mode: "0755" # Make executable
    remote_src: true # Source is on the remote host (downloaded to /tmp)
  when: xcaddy_version_changed

- name: Clean up xcaddy temporary files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/tmp/xcaddy_temp.tar.gz"
    - "/tmp/xcaddy"
  when: xcaddy_version_changed
