# roles/crowdsec/tasks/main.yml

# Conditional skip for the entire role if enable_crowdsec is false
- name: Skip CrowdSec role if disabled
  ansible.builtin.meta: end_play
  when: not enable_crowdsec | default(true)
  # Doc: Skips the entire CrowdSec role if `enable_crowdsec` is `false`. Defaults to `true` if undefined.

## Repository Installation Steps
# These tasks ensure the CrowdSec repository is added and packages can be installed.

- name: Ensure curl is installed
  ansible.builtin.apt:
    name: curl
    state: present
    update_cache: yes
  become: yes
  # Doc: Installs `curl`, a prerequisite for the CrowdSec repository setup script.

- name: Install CrowdSec repositories via script
  ansible.builtin.shell:
    cmd: curl -s https://install.crowdsec.net | sudo sh
    creates: /etc/apt/sources.list.d/crowdsec_crowdsec.list
  args:
    executable: /bin/bash
  become: yes
  # Doc: Executes the official CrowdSec script to add its APT repository. Idempotent via `creates`.

- name: Run apt update
  ansible.builtin.apt:
    update_cache: yes
  become: yes
  # Doc: Updates the APT cache after adding the new repository.

- name: Create CrowdSec data directory
  ansible.builtin.file:
    path: /var/lib/crowdsec
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: yes
  # Doc: Ensures the `/var/lib/crowdsec` data directory exists with proper permissions.

- name: Install CrowdSec and iptables bouncer
  ansible.builtin.apt:
    name:
      - crowdsec
      - crowdsec-firewall-bouncer-iptables
    state: present
  become: yes
  notify: restart crowdsec
  # Doc: Installs the CrowdSec agent and the `iptables` firewall bouncer. Notifies a restart if installed/updated.

## Post-Installation Configuration
# Tasks to ensure the CrowdSec service is running and its API is accessible.

- name: Ensure CrowdSec service is enabled and started
  ansible.builtin.systemd:
    name: crowdsec
    state: started
    enabled: yes
    daemon_reload: yes
  become: yes
  # Doc: Ensures the CrowdSec service is running, enabled at boot, and systemd reloads.

- name: Wait for CrowdSec Local API to be ready
  ansible.builtin.wait_for:
    port: {{ crowdsec_lapi_port }}
    host: {{ crowdsec_lapi_ip }}
    timeout: 60
    delay: 5
  delegate_to: localhost
  become: false
  when: inventory_hostname == 'prod_web_server'
  # Doc: Waits for the CrowdSec Local API on port 8080 to become accessible.

## CrowdSec Hub Initialization and Content Installation
# Installing necessary parsers and collections from the CrowdSec Hub.

- name: Update CrowdSec Hub
  ansible.builtin.command: cscli hub update
  register: cscli_hub_update_output
  changed_when: "'Nothing to do' not in cscli_hub_update_output.stdout"
  failed_when: cscli_hub_update_output.rc != 0
  become: yes
  # Doc: Updates the CrowdSec Hub to ensure access to the latest content.

- name: Install CrowdSecurity base HTTP scenarios
  ansible.builtin.command: cscli collections install crowdsecurity/base-http-scenarios
  register: cscli_base_http_scenarios_output
  changed_when: "'Successfully installed' in cscli_base_http_scenarios_output.stdout or 'Upgraded' in cscli_base_http_scenarios_output.stdout"
  failed_when: "(cscli_base_http_scenarios_output.rc != 0 and 'already installed' not in cscli_base_http_scenarios_output.stderr and 'already enabled' not in cscli_base_http_scenarios_output.stdout)"
  become: yes
  # Doc: Installs the core HTTP scenario collection for web attack detection.

- name: Install Caddy logs parser
  ansible.builtin.command: cscli parsers install crowdsecurity/caddy-logs
  register: cscli_caddy_logs_output
  changed_when: "'Successfully installed' in cscli_caddy_logs_output.stdout or 'Upgraded' in cscli_caddy_logs_output.stdout"
  failed_when: "(cscli_caddy_logs_output.rc != 0 and 'already installed' not in cscli_caddy_logs_output.stderr and 'already enabled' not in cscli_caddy_logs_output.stdout)"
  become: yes
  # Doc: Installs the Caddy log parser for CrowdSec to process Caddy access logs.

- name: Install generic HTTP logs parser (optional)
  ansible.builtin.command: cscli parsers install crowdsecurity/http-logs
  register: cscli_http_logs_output
  changed_when: "'Successfully installed' in cscli_http_logs_output.stdout or 'Upgraded' in cscli_http_logs_output.stdout"
  failed_when: "(cscli_http_logs_output.rc != 0 and 'already installed' not in cscli_http_logs_output.stderr and 'already enabled' not in cscli_http_logs_output.stdout)"
  become: yes
  # Doc: Installs a generic HTTP log parser for broader HTTP log processing.

## CrowdSec AppSec Installation and Configuration
# Installing AppSec-specific collections and configuring the AppSec listener.

- name: Install CrowdSec AppSec virtual patching collection
  ansible.builtin.command: cscli collections install crowdsecurity/appsec-virtual-patching
  register: cscli_appsec_virtual_patching_output
  changed_when: "'Successfully installed' in cscli_appsec_virtual_patching_output.stdout or 'Upgraded' in cscli_appsec_virtual_patching_output.stdout"
  failed_when: "(cscli_appsec_virtual_patching_output.rc != 0 and 'already installed' not in cscli_appsec_virtual_patching_output.stderr and 'already enabled' not in cscli_appsec_virtual_patching_output.stdout)"
  become: yes
  # Doc: Installs the AppSec virtual patching collection for vulnerability protection.

- name: Install CrowdSec AppSec generic rules collection
  ansible.builtin.command: cscli collections install crowdsecurity/appsec-generic-rules
  register: cscli_appsec_generic_rules_output
  changed_when: "'Successfully installed' in cscli_appsec_generic_rules_output.stdout or 'Upgraded' in cscli_appsec_generic_rules_output.stdout"
  failed_when: "(cscli_appsec_generic_rules_output.rc != 0 and 'already installed' not in cscli_appsec_generic_rules_output.stderr and 'already enabled' not in cscli_appsec_generic_rules_output.stdout)"
  become: yes
  # Doc: Installs generic AppSec rules for broad web application attack detection.

- name: Install CrowdSec AppSec HTTP CVE collection
  ansible.builtin.command: cscli collections install crowdsecurity/http-cve
  register: cscli_appsec_http_cve_output
  changed_when: "'Successfully installed' in cscli_appsec_http_cve_output.stdout or 'Upgraded' in cscli_appsec_http_cve_output.stdout"
  failed_when: "(cscli_appsec_http_cve_output.rc != 0 and 'already installed' not in cscli_appsec_http_cve_output.stderr and 'already enabled' not in cscli_appsec_http_cve_output.stdout)"
  become: yes
  # Doc: Installs the AppSec HTTP CVE collection for known vulnerability exploitation detection.

- name: Configure CrowdSec to listen for AppSec requests
  ansible.builtin.copy:
    content: |
      # /etc/crowdsec/acquis.d/appsec.yaml
      source: appsec
      appsec_config: crowdsecurity/appsec-default
      labels:
        type: appsec
      listen_addr: {{ crowdsec_appsec_ip }}:{{ crowdsec_appsec_port }}
    dest: /etc/crowdsec/acquis.d/appsec.yaml
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: restart crowdsec
  # Doc: Configures CrowdSec to enable its AppSec component and listen on `127.0.0.1:7422`.

## CrowdSec Console Enrollment (for engine management)
# Enroll the CrowdSec engine with the Central Console for monitoring and advanced features.

- name: Check if CrowdSec engine is already enrolled with the Console
  ansible.builtin.command: cscli console status -o json
  register: cscli_console_status
  changed_when: false
  failed_when: false
  become: yes
  # Doc: Checks the current enrollment status with the CrowdSec Central Console.

- name: Enroll CrowdSec engine with the Console
  ansible.builtin.command: "cscli console enroll --enable context {{ crowdsec_enrollment_key }}"
  register: console_enroll_output
  changed_when: "'Successfully enrolled with the Console' in console_enroll_output.stdout"
  failed_when: "console_enroll_output.rc != 0 and 'already enrolled' not in console_enroll_output.stderr and 'You are already enrolled' not in console_enroll_output.stdout"
  become: yes
  when:
    - enable_crowdsec | default(true)
    - crowdsec_enrollment_key is defined and crowdsec_enrollment_key | length > 0
    - cscli_console_status.rc == 0
    - (cscli_console_status.stdout | from_json).get('status', '') != 'ENROLLED'
  # Doc: Enrolls the CrowdSec engine with the Central Console using `crowdsec_enrollment_key`.

## CrowdSec Bouncer Registration (for local bouncer-to-engine communication)
# Register the Caddy bouncer with the local CrowdSec API. This is for the bouncer to get decisions.

- name: Check if Caddy bouncer is already registered
  ansible.builtin.command: cscli bouncers list -o json
  register: cscli_bouncers_list
  changed_when: false
  failed_when: false
  become: yes
  # Doc: Checks if the Caddy bouncer is already registered with the local CrowdSec API.

- name: Register Caddy bouncer with CrowdSec Local API
  ansible.builtin.command: "cscli bouncers add caddy-bouncer -k {{ crowdsec_api_key }}"
  when:
    - enable_crowdsec | default(true)
    - "'caddy-bouncer' not in cscli_bouncers_list.stdout"
    - cscli_bouncers_list.rc == 0
  register: bouncer_registration_output
  changed_when: bouncer_registration_output.rc == 0
  failed_when: bouncer_registration_output.rc != 0 and 'already exists' not in bouncer_registration_output.stderr
  become: yes
  # Doc: Registers the "caddy-bouncer" with the CrowdSec Local API using `crowdsec_api_key`.

- name: Configure CrowdSec to monitor Caddy logs
  ansible.builtin.copy:
    content: |
      # Use 'filenames' (plural) to specify multiple files or a glob pattern
      filenames:
        - "{{ caddy_log_dir }}/*.access.log"
      labels:
        type: caddy
    dest: /etc/crowdsec/acquis.d/caddy_logs.yaml
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: restart crowdsec
  # Doc: Configures CrowdSec to monitor Caddy access logs from `caddy_log_dir`.

## CrowdSec Ntfy Setup

- name: Ensure CrowdSec notifications directory exists
  ansible.builtin.file:
    path: /etc/crowdsec/notifications/
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: ntfy_enabled
  # Doc: Ensures the CrowdSec notifications directory exists if Ntfy is enabled.

- name: Create ntfy notification configuration file
  ansible.builtin.template:
    src: "templates/ntfy.yaml.j2"
    dest: /etc/crowdsec/notifications/ntfy.yaml
    owner: root
    group: root
    mode: "0644"
  notify: restart crowdsec
  when: ntfy_enabled
  # Doc: Creates the Ntfy notification configuration file from a template if Ntfy is enabled.

- name: Install GeoIP enrichment parser if enabled
  ansible.builtin.command:
    cmd: cscli hub install crowdsecurity/geoip-enrich
  register: geoip_install_output
  changed_when: "'already installed' not in geoip_install_output.stdout"
  notify: restart crowdsec
  when: ntfy_enabled
  # Doc: Installs the GeoIP enrichment parser for IP-based geo-location if Ntfy is enabled.

## Activate ntfy or dynamic increase of blocking time

- name: Create/Overwrite profiles.yaml
  ansible.builtin.template:
    src: "templates/profiles.yaml.j2"
    dest: /etc/crowdsec/profiles.yaml
    owner: root
    group: root
    mode: "0644"
  notify: restart crowdsec
  when: ntfy_enabled or duration_expr
  # Doc: Creates or updates `profiles.yaml` from a template, enabling Ntfy or dynamic blocking.