# roles/crowdsec/tasks/main.yml

# Conditional skip for the entire role if enable_crowdsec is false
- name: Skip CrowdSec role if disabled in group_vars/all.yml
  ansible.builtin.meta: end_play
  when: not enable_crowdsec | default(true)

## Repository Installation Steps
# These tasks ensure the CrowdSec repository is added and packages can be installed.

- name: Ensure curl is installed for repository setup script
  ansible.builtin.apt:
    name: curl
    state: present
    update_cache: yes
  become: yes

- name: Install CrowdSec repositories via official script
  ansible.builtin.shell:
    cmd: curl -s https://install.crowdsec.net | sudo sh
    creates: /etc/apt/sources.list.d/crowdsec_crowdsec.list # Use a marker file for idempotency
  args:
    executable: /bin/bash # Ensure a shell is used for the pipe
  become: yes

- name: Run apt update after repository installation (ensure cache is refreshed)
  ansible.builtin.apt:
    update_cache: yes
  become: yes

- name: Create CrowdSec data directory '/var/lib/crowdsec'
  ansible.builtin.file:
    path: /var/lib/crowdsec
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: yes

- name: Install CrowdSec and iptables firewall bouncer
  ansible.builtin.apt:
    name:
      - crowdsec
      - crowdsec-firewall-bouncer-iptables # For system-level firewall blocking via iptables
    state: present
  become: yes
  notify: restart crowdsec # Notify handler to restart/start CrowdSec if newly installed or updated

## Post-Installation Configuration
# Tasks to ensure the CrowdSec service is running and its API is accessible.

- name: Ensure CrowdSec service is enabled and started
  ansible.builtin.systemd:
    name: crowdsec
    state: started
    enabled: yes
    daemon_reload: yes # Ensures systemd reloads if service unit files changed
  become: yes

- name: Wait for CrowdSec Local API to be ready
  ansible.builtin.wait_for:
    port: 8080 # Default CrowdSec Local API port
    host: 127.0.0.1
    timeout: 60 # Wait up to 60 seconds
    delay: 5 # Check every 5 seconds
  delegate_to: localhost # Run this check from the Ansible control node
  become: false # This check doesn't require sudo on the control node
  when: inventory_hostname == 'prod_web_server' # Apply this check to your main CrowdSec host (or all if applicable)

## CrowdSec Hub Initialization and Content Installation
# Installing necessary parsers and collections from the CrowdSec Hub.

- name: Update CrowdSec Hub
  ansible.builtin.command: cscli hub update
  register: cscli_hub_update_output
  changed_when: "'Nothing to do' not in cscli_hub_update_output.stdout"
  failed_when: cscli_hub_update_output.rc != 0
  become: yes

- name: Install CrowdSecurity base HTTP scenarios collection
  ansible.builtin.command: cscli collections install crowdsecurity/base-http-scenarios
  register: cscli_base_http_scenarios_output
  changed_when: "'Successfully installed' in cscli_base_http_scenarios_output.stdout or 'Upgraded' in cscli_base_http_scenarios_output.stdout"
  failed_when: "(cscli_base_http_scenarios_output.rc != 0 and 'already installed' not in cscli_base_http_scenarios_output.stderr and 'already enabled' not in cscli_base_http_scenarios_output.stdout)"
  become: yes

- name: Install Caddy logs parser
  ansible.builtin.command: cscli parsers install crowdsecurity/caddy-logs
  register: cscli_caddy_logs_output
  changed_when: "'Successfully installed' in cscli_caddy_logs_output.stdout or 'Upgraded' in cscli_caddy_logs_output.stdout"
  failed_when: "(cscli_caddy_logs_output.rc != 0 and 'already installed' not in cscli_caddy_logs_output.stderr and 'already enabled' not in cscli_caddy_logs_output.stdout)"
  become: yes

- name: Install generic HTTP logs parser (optional, useful for other HTTP logs if present)
  ansible.builtin.command: cscli parsers install crowdsecurity/http-logs
  register: cscli_http_logs_output
  changed_when: "'Successfully installed' in cscli_http_logs_output.stdout or 'Upgraded' in cscli_http_logs_output.stdout"
  failed_when: "(cscli_http_logs_output.rc != 0 and 'already installed' not in cscli_http_logs_output.stderr and 'already enabled' not in cscli_http_logs_output.stdout)"
  become: yes

## CrowdSec AppSec Installation and Configuration
# Installing AppSec-specific collections and configuring the AppSec listener.

- name: Install CrowdSec AppSec virtual patching collection
  ansible.builtin.command: cscli collections install crowdsecurity/appsec-virtual-patching
  register: cscli_appsec_virtual_patching_output
  changed_when: "'Successfully installed' in cscli_appsec_virtual_patching_output.stdout or 'Upgraded' in cscli_appsec_virtual_patching_output.stdout"
  failed_when: "(cscli_appsec_virtual_patching_output.rc != 0 and 'already installed' not in cscli_appsec_virtual_patching_output.stderr and 'already enabled' not in cscli_appsec_virtual_patching_output.stdout)"
  become: yes

- name: Install CrowdSec AppSec generic rules collection
  ansible.builtin.command: cscli collections install crowdsecurity/appsec-generic-rules
  register: cscli_appsec_generic_rules_output
  changed_when: "'Successfully installed' in cscli_appsec_generic_rules_output.stdout or 'Upgraded' in cscli_appsec_generic_rules_output.stdout"
  failed_when: "(cscli_appsec_generic_rules_output.rc != 0 and 'already installed' not in cscli_appsec_generic_rules_output.stderr and 'already enabled' not in cscli_appsec_generic_rules_output.stdout)"
  become: yes

- name: Install CrowdSec AppSec HTTP CVE collection
  ansible.builtin.command: cscli collections install crowdsecurity/http-cve
  register: cscli_appsec_http_cve_output
  changed_when: "'Successfully installed' in cscli_appsec_http_cve_output.stdout or 'Upgraded' in cscli_appsec_http_cve_output.stdout"
  failed_when: "(cscli_appsec_http_cve_output.rc != 0 and 'already installed' not in cscli_appsec_http_cve_output.stderr and 'already enabled' not in cscli_appsec_http_cve_output.stdout)"
  become: yes

- name: Configure CrowdSec to listen for AppSec requests
  ansible.builtin.copy:
    content: |
      # /etc/crowdsec/acquis.d/appsec.yaml
      source: appsec
      appsec_config: crowdsecurity/appsec-default
      labels:
        type: appsec
      listen_addr: 127.0.0.1:7422 # Default AppSec listen address. Your web server bouncer must forward to this.
    dest: /etc/crowdsec/acquis.d/appsec.yaml
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: restart crowdsec

## CrowdSec Console Enrollment (for engine management)
# Enroll the CrowdSec engine with the Central Console for monitoring and advanced features.

- name: Check if CrowdSec engine is already enrolled with the Console
  ansible.builtin.command: cscli console status -o json
  register: cscli_console_status
  changed_when: false
  failed_when: false # Don't fail if cscli isn't ready or not enrolled yet
  become: yes

- name: Enroll CrowdSec engine with the Console
  ansible.builtin.command: "cscli console enroll --enable context {{ crowdsec_enrollment_key }}"
  register: console_enroll_output
  changed_when: "'Successfully enrolled with the Console' in console_enroll_output.stdout"
  failed_when: "console_enroll_output.rc != 0 and 'already enrolled' not in console_enroll_output.stderr and 'You are already enrolled' not in console_enroll_output.stdout"
  become: yes
  when:
    - enable_crowdsec | default(true)
    - crowdsec_enrollment_key is defined and crowdsec_enrollment_key | length > 0
    - cscli_console_status.rc == 0 # Ensure the status command itself ran successfully
    - (cscli_console_status.stdout | from_json).get('status', '') != 'ENROLLED'

## CrowdSec Bouncer Registration (for local bouncer-to-engine communication)
# Register the Caddy bouncer with the local CrowdSec API. This is for the bouncer to get decisions.

- name: Check if Caddy bouncer is already registered with CrowdSec Local API
  ansible.builtin.command: cscli bouncers list -o json
  register: cscli_bouncers_list
  changed_when: false
  failed_when: false # Don't fail if cscli isn't ready or no bouncers yet
  become: yes

- name: Register Caddy bouncer with CrowdSec Local API
  ansible.builtin.command: "cscli bouncers add caddy-bouncer -k {{ crowdsec_api_key }}"
  when:
    - enable_crowdsec | default(true) # Only if CrowdSec is enabled
    - "'caddy-bouncer' not in cscli_bouncers_list.stdout" # Only register if not already there
    - cscli_bouncers_list.rc == 0 # Only proceed if the `cscli bouncers list` command itself was successful
  register: bouncer_registration_output
  changed_when: bouncer_registration_output.rc == 0
  failed_when: bouncer_registration_output.rc != 0 and 'already exists' not in bouncer_registration_output.stderr
  become: yes

- name: Configure CrowdSec to monitor Caddy logs
  ansible.builtin.copy:
    content: |
      # Use 'filenames' (plural) to specify multiple files or a glob pattern
      filenames:
        - "{{ caddy_log_dir }}/*.access.log"  # This will catch blog.access.log, notify.access.log etc.
      labels:
        type: caddy
    dest: /etc/crowdsec/acquis.d/caddy_logs.yaml
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: restart crowdsec

  ## CrowdSec Ntfy Setup

- name: Ensure CrowdSec notifications directory exists
  ansible.builtin.file:
    path: /etc/crowdsec/notifications/
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: ntfy_enabled

- name: Create ntfy notification configuration file
  ansible.builtin.template:
    src: "templates/ntfy.yaml.j2"
    dest: /etc/crowdsec/notifications/ntfy.yaml
    owner: root
    group: root
    mode: "0644"
  notify: restart crowdsec
  when: ntfy_enabled

- name: Install GeoIP enrichment parser if enabled
  ansible.builtin.command:
    cmd: cscli hub install crowdsecurity/geoip-enrich
  register: geoip_install_output
  changed_when: "'already installed' not in geoip_install_output.stdout"
  notify: restart crowdsec
  when: ntfy_enabled

- name: Create/Overwrite profiles.yaml, activate ntfy or dynamic increase of blocking time
  ansible.builtin.template:
    src: "templates/profiles.yaml.j2"
    dest: /etc/crowdsec/profiles.yaml
    owner: root
    group: root
    mode: "0644"
  notify: restart crowdsec
  when: ntfy_enabled or duration_expr