# roles/caddy/handlers/main.yml

# --- Handlers for Caddy Service ---

- name: Restart Caddy Service
  ansible.builtin.systemd:
    name: caddy
    state: restarted
    daemon_reload: yes # Ensure systemd reloads Caddy's unit file if it changed