---
- name: ansible-rathole-webguard
  hosts: webservers
  become: yes

  # Pre-tasks: Prepare the system with required packages and directories
  pre_tasks:
    - name: Ensure APT cache is updated
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Install common necessary packages
      ansible.builtin.apt:
        name:
          - build-essential
          - curl
          - unzip
          - git
          - vim
          - htop
        state: present

    - name: Ensure /usr/local/bin exists
      ansible.builtin.file:
        path: /usr/local/bin
        state: directory
        mode: '0755'

  # Roles: Only install server components if rathole_role == "server"
  # crowdsec is optional and controlled by enable_crowdsec variable
  roles:
    - role: go_lang
      when: rathole_role == "server"
    - role: xcaddy
      when: rathole_role == "server"
    - role: caddy
      when: rathole_role == "server"
    - role: crowdsec
      when: rathole_role == "server" and enable_crowdsec
    - role: rathole  # Always install rathole role