# roles/rathole/tasks/main.yml

- name: Ensure Rathole system group exists
  ansible.builtin.group:
    name: "{{ rathole_group }}"
    state: present

- name: Ensure Rathole system user exists
  ansible.builtin.user:
    name: "{{ rathole_user }}"
    group: "{{ rathole_group }}"
    create_home: false
    system: true
    shell: "/usr/sbin/nologin"
    state: present

- name: Check existing Rathole version
  ansible.builtin.command: "{{ rathole_install_path }}/{{ rathole_binary_name }} --version"
  register: rathole_version_check
  failed_when: false
  changed_when: false
  ignore_errors: true

- name: Extract Rathole version from output
  ansible.builtin.set_fact:
    rathole_installed_version: "{{ rathole_version_check.stdout | regex_search('Build Version:\\s+([0-9.]+)', '\\1') }}"
  when: rathole_version_check.rc == 0

- name: Set Rathole download URL based on architecture
  ansible.builtin.set_fact:
    rathole_download_url: "{{ rathole_download_url_base }}/{{ rathole_binary_name }}-{{ ansible_system | lower }}-{{ ansible_architecture }}"

- name: Display version difference
  ansible.builtin.debug:
    msg: >
      Rathole installed version: {{ rathole_installed_version | default('not installed') }},
      Target version: {{ rathole_version }}
  when: (rathole_installed_version | default('not installed')) != rathole_version

- name: Download Rathole binary
  ansible.builtin.get_url:
    url: "{{ rathole_download_url }}"
    dest: "/tmp/{{ rathole_binary_name }}"
    mode: "0755" # Make executable
  register: rathole_download_result
  until: rathole_download_result is succeeded
  retries: 5
  delay: 2 # Retry download up to 5 times with a 2-second delay
  when: (rathole_installed_version | default('not installed')) != rathole_version

- name: Move Rathole binary to /usr/local/bin
  ansible.builtin.copy:
    src: "/tmp/{{ rathole_binary_name }}"
    dest: "{{ rathole_install_path }}/{{ rathole_binary_name }}"
    owner: root
    group: root
    mode: "0755"
    remote_src: true # Source is on the remote host (downloaded to /tmp)
  when: (rathole_installed_version | default('not installed')) != rathole_version

- name: Create Rathole configuration directory
  ansible.builtin.file:
    path: "{{ rathole_config_path }}"
    state: directory
    owner: "{{ rathole_user }}"
    group: "{{ rathole_group }}"
    mode: "0755"
    recurse: true

- name: Create or update Rathole configuration file
  ansible.builtin.template:
    src: "templates/rathole.toml.j2"
    dest: "{{ rathole_config_path }}/{{ rathole_config_file }}"
    owner: "{{ rathole_user }}"
    group: "{{ rathole_group }}"
    mode: "0644"
  notify: Restart Rathole Service
  register: rathole_config_changed

- name: Create Systemd unit file for Rathole
  ansible.builtin.template:
    src: "templates/rathole.service.j2"
    dest: "/etc/systemd/system/rathole.service"
    owner: root
    group: root
    mode: "0644"
  notify:
    - Reload Systemd Daemon
    - Restart Rathole Service
  register: rathole_service_changed

  # Systemd daemon reload is handled by a handler triggered above

- name: Enable and start Rathole service
  ansible.builtin.systemd:
    name: rathole
    enabled: true
    state: started
  when: rathole_config_changed.changed or rathole_service_changed.changed

- name: Clean up temporary Rathole files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/tmp/{{ rathole_binary_name }}"
