# roles/crowdsec/handlers/main.yml

# --- Handlers for Crowdsec Service ---

- name: Restart Crowdsec Service
  ansible.builtin.systemd:
    name: crowdsec
    state: restarted
    daemon_reload: true
