---
galaxy_info:
  author: chrisvgt
  description: Install and manage Rathole service
  license: MIT
  min_ansible_version: '2.14'
  platforms:
    - name: Debian
      versions: ['bullseye', 'bookworm']
    - name: Ubuntu
      versions: ['focal', 'jammy', 'noble']
  galaxy_tags:
    - tunnel
    - reverseproxy
    - rathole

dependencies: []
