xcaddy_version: "0.4.4"
xcaddy_download_url: "https://github.com/caddyserver/xcaddy/releases/download/v{{ xcaddy_version }}/xcaddy_{{ xcaddy_version }}_linux_amd64.tar.gz" # Adjust for other architectures if needed
xcaddy_install_path: "/usr/local/bin"