---
galaxy_info:
  author: chrisvgt
  description: Install and configure Caddy with optional plugins (Cloudflare, CrowdSec)
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions: ["bullseye", "bookworm"]
    - name: Ubuntu
      versions: ["focal", "jammy", "noble"]
  galaxy_tags:
    - caddy
    - http
    - reverseproxy
    - tls
    - crowdsec
    - cloudflare

dependencies: []
