name: Lint Ansible

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install yamllint ansible ansible-lint

      - name: Yamllint
        run: |
          yamllint -s .

      - name: Ansible-lint
        env:
          ANSIBLE_DEPRECATION_WARNINGS: 'false'
        run: |
          ansible-lint -v site.yml
