name: Lint Ansible

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install yamllint ansible ansible-lint pre-commit

      - name: Yamllint (warnings allowed)
        run: |
          # Yamllint exits non-zero for errors only; we've configured most style issues as warnings.
          yamllint -s .

      - name: Ansible-lint
        env:
          ANSIBLE_DEPRECATION_WARNINGS: "false"
        run: |
          ansible-lint -v site.yml

      - name: Pre-commit (format checks)
        run: |
          pre-commit install-hooks
          pre-commit run --all-files || (
            echo "Pre-commit checks failed. Please run 'pre-commit run --all-files' locally to auto-fix." && exit 1
          )
